
# appspec.yml
version: 0.0
os: linux

files:
  - source: backend
    destination: /home/ec2-user/backend
  - source: frontend-build
    destination: /var/www/frontend

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
