
version: 0.2

phases:
  install:
    commands:
      - echo "Checking build environment..."
      - pwd
      - ls -la
      - echo "Node.js version:"
      - node --version
      - echo "npm version:"
      - npm --version

  build:
    commands:
      - echo "Checking project structure..."
      - find . -type d -name "frontend" -o -name "backend" | head -10
      - echo "Installing backend dependencies..."
      - cd backend && npm install && cd ..
      - echo "Attempting frontend build..."
      - cd frontend
      - npm install --legacy-peer-deps --verbose
      - npm run build
      - cd ..
      - echo "Creating deployment package..."
      - mkdir -p deployment
      - cp -r backend deployment/
      - cp -r frontend/build deployment/frontend-build
      - cp appspec.yml deployment/
      - cp -r scripts deployment/

artifacts:
  files:
    - '**/*'
  base-directory: deployment
