version: 0.2

phases:
  install:
    commands:
      - echo "Starting build process"
      - pwd
      - ls -la
  pre_build:
    commands:
      - echo "Installing backend dependencies"
      - cd backend && npm install
      - cd ..
  build:
    commands:
      - echo "Building frontend"
      - cd frontend && npm install
      - npm run build
      - cd ..
  post_build:
    commands:
      - echo "Creating deployment package"
      - mkdir -p deployment
      - cp -r backend deployment/
      - cp -r frontend/build deployment/frontend-build
      - ls -la deployment/

artifacts:
  files:
    - '**/*'
  base-directory: deployment
