version: 0.2
phases:
  install:
    commands:
      - echo "Starting build"
  pre_build:
    commands:
      - echo "Installing backend"
      - cd backend && npm install
  build:
    commands:
      - echo "Building frontend"
      - cd frontend && npm install
      - npm run build
  post_build:
    commands:
      - echo "Creating deployment"
      - mkdir -p deployment
      - cp -r backend deployment/
      - cp -r frontend/build deployment/frontend-build
artifacts:
  files:
    - '**/*'
  base-directory: deployment
