
version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js..."
      - curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
      - yum install -y nodejs
      - echo "Node.js version: $(node --version)"
      - echo "npm version: $(npm --version)"

  pre_build:
    commands:
      - echo "Installing backend dependencies..."
      - cd backend && npm install
      - cd ..

  build:
    commands:
      - echo "Building frontend..."
      - cd frontend && npm install
      - npm run build
      - cd ..

  post_build:
    commands:
      - echo "Creating deployment package..."
      - mkdir -p deployment
      - cp -r backend deployment/
      - cp -r frontend/build deployment/frontend-build
      - cp scripts/deploy.sh deployment/
      - echo "Deployment package ready"

artifacts:
  files:
    - '**/*'
  base-directory: deployment
