
version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - cd backend && npm install && cd ..
      - cd frontend && npm install

  build:
    commands:
      - echo "Building application..."
      - cd frontend && npm run build
      - echo "Build completed at $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
