version: 0.2

phases:
  install:
    commands:
      - echo "Installing specific Node.js version..."
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - apt-get install -y nodejs
      - echo "Node.js version:"
      - node --version
      - echo "npm version:"
      - npm --version
      - echo "Installing frontend dependencies..."
      - cd frontend && npm install --legacy-peer-deps
      - cd ..

  pre_build:
    commands:
      - echo "Installing backend dependencies..."
      - cd backend && npm install
      - cd ..

  build:
    commands:
      - echo "Building frontend..."
      - cd frontend
      - npm run build
      - cd ..
      - echo "Creating deployment package..."
      - mkdir -p deployment/backend
      - mkdir -p deployment/frontend-build
      - cp -r backend/* deployment/backend/
      - cp -r frontend/build/* deployment/frontend-build/
      - cp appspec.yml deployment/
      - cp -r scripts deployment/

artifacts:
  files:
    - '**/*'
  base-directory: deployment
